### ISSUE TITLE
"4294967295" New messages

### ISSUE THREAD

**Issue by streaps** [askovpen/gossiped#141]
A few areas show "4294967295" new messages in the area list instead of "0". Like:

```
║ Area EchoID             Msgs        New║
║  42+ UTF-8                49 4294967295║
```
Gossiped 2.0.7 ARMv7 on Raspian Buster

**Comment by streaps** [comment]
All my areas are JAM, the areafile is crashmail.

**Comment by streaps** [comment]
I also can not enter that areas
```
$ gossiped
2020/01/16 09:17:43 gossipEd-linux/arm 2.0.7-b274c49a started
panic: runtime error: index out of range [49] with length 49 [recovered]
        panic: runtime error: index out of range [49] with length 49

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1(0xdb4be0)
        /home/travis/gopath/pkg/mod/github.com/rivo/tview@v0.0.0-20200108161608-1316ea7a4b35/application.go:149 +0x6c
panic(0x2064b0, 0x10fbb50)
        /home/travis/.gimme/versions/go1.13.linux.amd64/src/runtime/panic.go:679 +0x194
github.com/askovpen/gossiped/pkg/msgapi.(*JAM).GetMsg(0xd6a640, 0x32, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/askovpen/gossiped/pkg/msgapi/jam.go:107 +0x1588
github.com/askovpen/gossiped/pkg/ui.(*App).ViewMsg(0xd6acc0, 0x2a, 0x32, 0x0, 0x2, 0x10fbb20, 0x10, 0xd6ad30)
        /home/travis/gopath/src/github.com/askovpen/gossiped/pkg/ui/viewmsg.go:16 +0x50
github.com/askovpen/gossiped/pkg/ui.(*App).onSelected(0xd6acc0, 0x2b, 0x0)
        /home/travis/gopath/src/github.com/askovpen/gossiped/pkg/ui/arealist.go:105 +0x2c4
github.com/askovpen/gossiped/pkg/ui.(*App).AreaList.func2(0x2b, 0x0)
        /home/travis/gopath/src/github.com/askovpen/gossiped/pkg/ui/arealist.go:48 +0x2c
github.com/rivo/tview.(*Table).InputHandler.func1(0xcee8a0, 0xc0e490)
        /home/travis/gopath/pkg/mod/github.com/rivo/tview@v0.0.0-20200108161608-1316ea7a4b35/table.go:1163 +0x2b4
github.com/rivo/tview.(*Box).WrapInputHandler.func1(0xcee8a0, 0xc0e490)
        /home/travis/gopath/pkg/mod/github.com/rivo/tview@v0.0.0-20200108161608-1316ea7a4b35/box.go:160 +0x50
github.com/rivo/tview.(*Application).Run(0xdb4be0, 0x0, 0x0)
        /home/travis/gopath/pkg/mod/github.com/rivo/tview@v0.0.0-20200108161608-1316ea7a4b35/application.go:234 +0x2c8
github.com/askovpen/gossiped/pkg/ui.(*App).Run(0xd6acc0, 0x1, 0x1)
        /home/travis/gopath/src/github.com/askovpen/gossiped/pkg/ui/app.go:38 +0x44
main.main()
        /home/travis/gopath/src/github.com/askovpen/gossiped/gossiped.go:74 +0x3c0

```

**Comment by askovpen** [comment]
pls send jam-database to spam-from-github at skovpen.org

**Comment by askovpen** [comment]
`cat /proc/cpuinfo`

```
model name      : ARMv7 Processor rev 1 (v7l)
Features        : half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
```

test on debian armhf with your jam database - work fine.

**Comment by streaps** [comment]
It's a weird bug. All the echoareas have a last read pointer on the latest message ("0" unread messages), but only a few show "4294967295". 

the only difference i see is thumbee:

```
cat /proc/cpuinfo
model name      : ARMv7 Processor rev 5 (v7l)
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
```

**Comment by askovpen** [comment]
you have 49 messages in area, but lastread position - 51.

**Comment by askovpen** [comment]
your base have BaseMsgNumber=3 (first message number)

**Comment by streaps** [comment]
deleted and purged messages?

I can confirm that it's fixed for all other areas too. thanks
